### ISSUE TITLE
[documentation] Regex Matching: You *must* specify a regex.

### ISSUE THREAD

**Issue by aars** [achiu/rack-parser#15]
Since `String.match` is used, all matching is done as a regex. This causes some content_types that contain regex special chars to not match. JSONAPI content_type is `application/vnd.api+json` for example. This will never match if you do not treat the `Rack::Parser` config keys as regexes.

```
use Rack::Parser, :parsers => {
  'application/vnd.api+json' => Rack::Parser::JSONAPI.new, # This never matches...
  'application/json'         => Rack::Parser::JSON.new
}

[5] pry(#<Rack::Parser>)> 'application/json.api+json'.match('application/json.api+json')
=> nil
```

This could be considered a documentation issue.

It could also be considered a bug, but that means that regex's need to be passed explicitly. I'll submit a PR for that. It's up to you to decide how to handle this.

Or, is this lib abandoned? Seeing that there are some pretty old open PRs.

**Comment by achiu** [comment]
I've merged a PR to make regex matching explicit and released a new version on rubygems https://github.com/achiu/rack-parser/releases/tag/v0.7.0. Let me know if this solves your issue.
